// Generated by CoffeeScript 1.6.3
(function() {
  var app;

  $(document).ready(function() {
    app.init();
  });

  app = (function() {
    "use strict";
    var arlesPosition, bnpPosition, boilerPosition, headerFixed, init, natumPosition, ocoPosition, onefeatPosition, resetPosition, the_id, tweetPosition;
    headerFixed = onefeatPosition = natumPosition = tweetPosition = boilerPosition = bnpPosition = ocoPosition = arlesPosition = the_id = 0;
    init = function() {
      $.stellar({
        horizontalScrolling: false,
        verticalOffset: 0
      });
      resetPosition();
      $(window).resize(function() {
        resetPosition();
      });
      $("#fake_header .about, #fake_header .what").click(function(e) {
        e.preventDefault();
        the_id = $(this).attr("href");
        $('.collapsible.description').addClass('open');
        setTimeout(function() {
          $('html, body').animate({
            scrollTop: $(the_id).offset().top
          }, '500');
          resetPosition();
        }, 500);
        return false;
      });
      $('a[href^="#"]').click(function() {
        the_id = $(this).attr("href");
        if (the_id === "#aboutme" || the_id === "#whatiknow") {
          return false;
        }
        $('html, body').animate({
          scrollTop: $(the_id).offset().top - 70
        }, '500');
        return false;
      });
      $('.collapsible').click(function() {
        $(this).toggleClass('open');
        setTimeout(function() {
          resetPosition();
        }, 500);
      });
      $(document).scroll(function() {
        var projectsPosition, scroll;
        scroll = $(document).scrollTop();
        projectsPosition = $("#projects").position();
        if (scroll < projectsPosition.top) {
          if (headerFixed === true) {
            $("#projects").attr('class', '');
            $("#header .active").removeClass("active");
            headerFixed = false;
          }
        } else {
          headerFixed = true;
          $("#projects").addClass("fixed");
          scroll = scroll + 100;
          if (scroll > bnpPosition.top) {
            $("#projects").attr("class", "fixed bnp");
          } else if (scroll > tweetPosition.top) {
            $("#projects").attr("class", "fixed tweet");
          } else if (scroll > boilerPosition.top) {
            $("#projects").attr("class", "fixed boiler");
          } else if (scroll > arlesPosition.top) {
            $("#projects").attr("class", "fixed arles");
          } else if (scroll > ocoPosition.top) {
            $("#projects").attr("class", "fixed oco");
          } else if (scroll > natumPosition.top) {
            $("#projects").attr("class", "fixed natum");
          } else if (scroll > onefeatPosition.top) {
            $("#projects").attr("class", "fixed onefeat");
          }
        }
      });
    };
    resetPosition = function() {
      $('#projects .photo').height(window.innerWidth / 1.6);
      if (window.innerWidth > 1600 || window.innerWidth < 800) {
        $('#projects .photo').addClass('responsive');
      } else {
        $('#projects .responsive').removeClass('responsive');
      }
      $.stellar('refresh');
      onefeatPosition = $("#onefeat").position();
      natumPosition = $("#natum").position();
      arlesPosition = $("#arles").position();
      tweetPosition = $("#tweet").position();
      ocoPosition = $("#oco").position();
      bnpPosition = $("#bnp").position();
      boilerPosition = $("#boiler").position();
    };
    return {
      init: init
    };
  })();

}).call(this);
