// Generated by CoffeeScript 1.6.3
(function() {
  var app;

  $(document).ready(function() {
    app.init();
  });

  app = (function() {
    "use strict";
    var artofmakingPosition ,printidentityPosition, digitalPosition, contactPosition, init, resetPosition, the_id,isHovered,sideMargin ;
    artofmakingPosition ,printidentityPosition, digitalPosition,contactPosition,sideMargin = 0;

    init = function() {
      // $.stellar({
      //   horizontalScrolling: false,
      //   verticalOffset: 0
      // });

      resetPosition();

      $(window).resize(function() {
        resetPosition();
      });

      $('#navbar a[href^="#"]').click(function() {
        the_id = $(this).attr("href");
        console.log(the_id);
        $('html, body').animate({
          scrollTop: $(the_id).offset().top + window.innerHeight
        }, '500');
        return false;
      });

      $(".projects a").click(function(event){
        $("html").addClass('overlayvisible');
        var id = $(this).attr('data-id');
        $("#overlay .project").hide();

        var elem = $("#overlay").find("#"+id);
        elem.show();
        elem.parent('.container').scrollTop(0);
        event.preventDefault();
        return false;
      });

    //  var delay=300, setTimeoutConst;
      // $(".projects a").mouseover(function(){
      // //  setTimeoutConst = setTimeout(function(){
      //     $("#content").addClass("blur");
      //   //}, delay);
      //   //$("#content").addClass("blur");
      // }).mouseout(function(){

      //   $("#content").removeClass("blur");
      // //  clearTimeout(setTimeoutConst );
      // });

      //OVERLAY BLUR
      $("#overlay").click(function(){

          if(!isHovered)
          {
            $("html").removeClass('overlayvisible');
            $(this).removeClass('closable');
            $(this).removeClass('blur');

          }


      });

      // $("#overlay").mousemove(function(e){
      //   if(e.clientX < sideMargin || e.clientX > (sideMargin + 800)){
      //     $("#overlay").addClass('blur');
      //   }else{
      //     $("#overlay").removeClass('blur');
      //   }
      // });

      // $('#overlay img').hover(function()
      // {
      //   isHovered = true;
      //   $("#overlay").removeClass('closable blur');
      // }, function(e){
      //   isHovered = false;
      //   $("#overlay").addClass('closable');
      // });

      // $("#overlay").mouseover(function(){
      //     if($("#overlay img").hover())
      //     {
      //       console.log('hover');
      //         $("#overlay").removeClass('blur');
      //     }else
      //     {
      //       console.log('out');
      //       $("#overlay").addClass('blur');
      //     }
      // });

      $('.collapsible').click(function() {
        $(this).toggleClass('open');
        setTimeout(function() {
          resetPosition();
        }, 500);
      });


      $(document).scroll(function() {

        var ratioAlpha = 0;
        var scroll = $(document).scrollTop() + 100;
        if (scroll > contactPosition.top) {
          $("#navbar ul").attr("class", "contact");

        } else if (scroll >  digitalPosition.top) {
          $("#navbar ul").attr("class", "digital");

          ratioAlpha = (scroll - digitalPosition.top) / window.innerHeight;
          $("#digital .photo_blur").css("opacity",ratioAlpha);

        } else if (scroll >  artofmakingPosition.top) {
          $("#navbar ul").attr("class", "artofmaking");

          ratioAlpha = (scroll - artofmakingPosition.top) / window.innerHeight;
          $("#artofmaking .photo_blur").css("opacity",ratioAlpha);
          $("#digital .photo_blur").css("opacity",0);

        } else if (scroll >  printidentityPosition.top) {
          $("#navbar ul").attr("class", "printidentity");
     
          ratioAlpha = (scroll - printidentityPosition.top) /  window.innerHeight;
          $("#printidentity .photo_blur").css("opacity",ratioAlpha);
          $("#artofmaking .photo_blur").css("opacity",0);

        }else
        {
          $("#printidentity .photo_blur").css("opacity",0);
          $("#navbar ul").attr("class", "");
        }


      });

  
  

    };
    resetPosition = function() {
      sideMargin = (window.innerWidth -800) / 2;
      var minHeight = 470*2;
      if(window.innerHeight*2 > minHeight)
      {
        $('#content .projects').height(window.innerHeight*2);
      }else
      {
        $('#content .projects').height(minHeight);
      }

      if (window.innerWidth > 1600 || window.innerWidth < 800) {
        $('#projects .photo').addClass('responsive');
      } else {
        $('#projects .responsive').removeClass('responsive');
      }
      // $.stellar('refresh');

      printidentityPosition = $("#printidentity").position();
      artofmakingPosition = $("#artofmaking").position();
      digitalPosition = $("#digital").position();
      contactPosition = $("#contact").position();

    };
    return {
      init: init
    };
  })();

}).call(this);
